### ISSUE TITLE
boost python vc10 and boost regex vc10 for boost 1.61

### ISSUE THREAD

**Issue by bbusacker** [sergey-shandar/getboost#23]
Any plans to provide support for regex and python for vc10?

**Comment by sergey-shandar** [comment]
Should be fixed for Boost 1.62.

**Comment by bbusacker** [comment]
Still appears to be broken.  regex and python don't show up as being able to upgrade to 1.62

**Comment by sergey-shandar** [comment]
Try these links https://github.com/sergey-shandar/getboost/blob/master/releases/1.62.md#libraries

In particular: 
- python [vc100](http://nuget.org/packages/boost_python-vc100/1.62.0.0) [vc110](http://nuget.org/packages/boost_python-vc110/1.62.0.0) [vc120](http://nuget.org/packages/boost_python-vc120/1.62.0.0) [vc140](http://nuget.org/packages/boost_python-vc140/1.62.0.0) [vc80](http://nuget.org/packages/boost_python-vc80/1.62.0.0) [vc90](http://nuget.org/packages/boost_python-vc90/1.62.0.0)
- regex [vc100](http://nuget.org/packages/boost_regex-vc100/1.62.0.0) [vc110](http://nuget.org/packages/boost_regex-vc110/1.62.0.0) [vc120](http://nuget.org/packages/boost_regex-vc120/1.62.0.0) [vc140](http://nuget.org/packages/boost_regex-vc140/1.62.0.0) [vc80](http://nuget.org/packages/boost_regex-vc80/1.62.0.0) [vc90](http://nuget.org/packages/boost_regex-vc90/1.62.0.0)
